/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedStudiesIdRouteImport } from './routes/_authenticated/studies.$id'
import { Route as AuthenticatedStudiesIdResponsesRouteImport } from './routes/_authenticated/studies.$id.responses'
import { Route as AuthenticatedStudiesIdSessionsSessionIdRouteImport } from './routes/_authenticated/studies.$id.sessions.$sessionId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudiesIdRoute = AuthenticatedStudiesIdRouteImport.update({
  id: '/studies/$id',
  path: '/studies/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudiesIdResponsesRoute =
  AuthenticatedStudiesIdResponsesRouteImport.update({
    id: '/responses',
    path: '/responses',
    getParentRoute: () => AuthenticatedStudiesIdRoute,
  } as any)
const AuthenticatedStudiesIdSessionsSessionIdRoute =
  AuthenticatedStudiesIdSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AuthenticatedStudiesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/studies/$id': typeof AuthenticatedStudiesIdRouteWithChildren
  '/studies/$id/responses': typeof AuthenticatedStudiesIdResponsesRoute
  '/studies/$id/sessions/$sessionId': typeof AuthenticatedStudiesIdSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/studies/$id': typeof AuthenticatedStudiesIdRouteWithChildren
  '/studies/$id/responses': typeof AuthenticatedStudiesIdResponsesRoute
  '/studies/$id/sessions/$sessionId': typeof AuthenticatedStudiesIdSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/studies/$id': typeof AuthenticatedStudiesIdRouteWithChildren
  '/_authenticated/studies/$id/responses': typeof AuthenticatedStudiesIdResponsesRoute
  '/_authenticated/studies/$id/sessions/$sessionId': typeof AuthenticatedStudiesIdSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/studies/$id'
    | '/studies/$id/responses'
    | '/studies/$id/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/studies/$id'
    | '/studies/$id/responses'
    | '/studies/$id/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/studies/$id'
    | '/_authenticated/studies/$id/responses'
    | '/_authenticated/studies/$id/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studies/$id': {
      id: '/_authenticated/studies/$id'
      path: '/studies/$id'
      fullPath: '/studies/$id'
      preLoaderRoute: typeof AuthenticatedStudiesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studies/$id/responses': {
      id: '/_authenticated/studies/$id/responses'
      path: '/responses'
      fullPath: '/studies/$id/responses'
      preLoaderRoute: typeof AuthenticatedStudiesIdResponsesRouteImport
      parentRoute: typeof AuthenticatedStudiesIdRoute
    }
    '/_authenticated/studies/$id/sessions/$sessionId': {
      id: '/_authenticated/studies/$id/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/studies/$id/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedStudiesIdSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedStudiesIdRoute
    }
  }
}

interface AuthenticatedStudiesIdRouteChildren {
  AuthenticatedStudiesIdResponsesRoute: typeof AuthenticatedStudiesIdResponsesRoute
  AuthenticatedStudiesIdSessionsSessionIdRoute: typeof AuthenticatedStudiesIdSessionsSessionIdRoute
}

const AuthenticatedStudiesIdRouteChildren: AuthenticatedStudiesIdRouteChildren =
  {
    AuthenticatedStudiesIdResponsesRoute: AuthenticatedStudiesIdResponsesRoute,
    AuthenticatedStudiesIdSessionsSessionIdRoute:
      AuthenticatedStudiesIdSessionsSessionIdRoute,
  }

const AuthenticatedStudiesIdRouteWithChildren =
  AuthenticatedStudiesIdRoute._addFileChildren(
    AuthenticatedStudiesIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedStudiesIdRoute: typeof AuthenticatedStudiesIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedStudiesIdRoute: AuthenticatedStudiesIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
